### ISSUE TITLE
Error: Cannot find module '@iconify/json'

### ISSUE THREAD

**Issue by Septias** [antfu/vite-plugin-icons#4]
I just installed it with npm and added:
`import IconAccessibility from "/@vite-icons/carbon/accessibility.vue";`
Now I get: 
```
failed to load config from C:\dev\repositories\BettIlias\Frontend\vite.config.ts
error when starting dev server:
Error: Cannot find module '@iconify/json'
Require stack:
- C:\dev\repositories\BettIlias\Frontend\node_modules\.pnpm\vite-plugin-icons@0.2.1_@vue+compiler-sfc@3.0.5\node_modules\vite-plugin-icons\dist\index.js
- C:\dev\repositories\BettIlias\Frontend\vite.config.ts
- C:\dev\repositories\BettIlias\Frontend\node_modules\.pnpm\vite@2.0.0-beta.10\node_modules\vite\dist\node\chunks\dep-0b3d3f5e.js
- C:\dev\repositories\BettIlias\Frontend\node_modules\.pnpm\vite@2.0.0-beta.10\node_modules\vite\dist\node\cli.js
- C:\dev\repositories\BettIlias\Frontend\node_modules\.pnpm\vite@2.0.0-beta.10\node_modules\vite\bin\vite.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\dev\repositories\BettIlias\Frontend\node_modules\.pnpm\vite-plugin-icons@0.2.1_@vue+compiler-sfc@3.0.5\node_modules\vite-plugin-icons\dist\index.js:74:13)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
 ERROR  Command failed with exit code 1.
```

**Comment by antfu** [comment]
Duplicated #2
